<a href="https://colab.research.google.com/github/khushimalik3122/salary-predictor-19/blob/main/sp_19_outlier_cleaner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
df_original = pd.read_csv("/content/drive/MyDrive/sp_19_app/cleaned_dataset.csv")

In [ ]:
df_original.describe()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1882.000000,1882.000000,1882.000000,1882.000000,1882.0,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000
mean,1015.179065,1068.931456,1111.293836,3.266578,0.0,53.773645,90.071732,71.697662,747.840595,36.298087,4.251692
std,591.606503,625.983745,667.517755,1.377824,0.0,14.672204,19.282413,15.900123,435.806632,12.904956,0.218585
min,0.000000,0.000000,0.000000,0.000000,0.0,30.000000,53.000000,41.000000,0.000000,6.000000,3.725693
25%,500.250000,529.250000,529.250000,3.100000,0.0,43.000000,76.000000,59.000000,358.250000,29.000000,4.085976
50%,998.500000,1056.500000,1085.500000,3.600000,0.0,51.000000,87.000000,69.000000,759.000000,36.000000,4.241327
75%,1525.750000,1583.750000,1670.750000,4.000000,0.0,60.000000,103.000000,80.000000,1146.750000,46.000000,4.382027
max,2024.000000,2137.000000,2252.000000,5.000000,0.0,98.000000,132.000000,113.000000,1501.000000,64.000000,4.727388

In [ ]:
import numpy as np

# Define the columns and methods
columns = {
    'Rating': 'IQR',
    'Easy Apply': 'Z-Score',
    'Min Salary (K)': 'IQR',
    'Max Salary (K)': 'IQR',
    'Avg Salary (K)': 'IQR',
    'Company_Encoded': 'None',
    'Salary Range (K)': 'IQR',
    'Log Avg Salary': 'Z-Score'
}

# Define the thresholds
thresholds = {
    'Easy Apply': 2,
    'Log Avg Salary': 2
}

# Apply the methods
for column, method in columns.items():
    if method == 'IQR':
        Q1 = df_original[column].quantile(0.25)
        Q3 = df_original[column].quantile(0.75)
        IQR = Q3 - Q1
        df = df_original[~((df_original[column] < (Q1 - 1.5 * IQR)) | (df_original[column] > (Q3 + 1.5 * IQR)))]
    elif method == 'Z-Score':
        threshold = thresholds[column]
        z_scores = np.abs((df_original[column] - df_original[column].mean()) / df_original[column].std())
        df = df_original[z_scores < threshold]
    elif method == 'None':
        pass  # No outlier removal for this column

print("Original dataset shape:", df_original.shape)
print("Filtered dataset shape:", df.shape)

Original dataset shape: (1882, 174)
Filtered dataset shape: (1806, 174)

In [ ]:
df.describe()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1806.000000,1806.000000,1806.000000,1806.000000,1806.0,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000
mean,1016.775748,1070.420266,1113.347176,3.268439,0.0,53.654485,90.344961,71.773533,743.646733,36.690476,4.256826
std,599.331402,634.337523,676.201879,1.373428,0.0,13.385410,18.135166,14.568786,435.563107,12.999680,0.198270
min,0.000000,0.000000,0.000000,0.000000,0.0,34.000000,61.000000,47.000000,1.000000,6.000000,3.860730
25%,493.250000,522.250000,522.250000,3.100000,0.0,43.000000,76.000000,60.000000,350.250000,29.000000,4.102643
50%,1002.500000,1060.500000,1089.500000,3.600000,0.0,51.000000,87.000000,70.000000,753.500000,37.000000,4.248495
75%,1540.750000,1598.750000,1685.750000,4.000000,0.0,60.000000,103.000000,79.000000,1133.750000,46.000000,4.375757
max,2024.000000,2137.000000,2252.000000,5.000000,0.0,98.000000,132.000000,106.000000,1501.000000,64.000000,4.663439

In [ ]:
columns = {
    'Rating': 'IQR',
    'Easy Apply': 'None',
    'Min Salary (K)': 'IQR',
    'Max Salary (K)': 'IQR',
    'Avg Salary (K)': 'IQR',
    'Company_Encoded': 'None',
    'Salary Range (K)': 'IQR',
    'Log Avg Salary': 'IQR'
}

# Apply the methods
for column, method in columns.items():
    if method == 'IQR':
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        df_filtered = df[~((df[column] < (Q1 - 2.5 * IQR)) | (df[column] > (Q3 + 2.5 * IQR)))]
    elif method == 'None':
        pass  # No outlier removal for this column

print("Original dataset shape:", df_original.shape)
print("Filtered dataset shape:", df_filtered.shape)

Original dataset shape: (1882, 174)
Filtered dataset shape: (1806, 174)

In [ ]:
df_filtered.describe()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1806.000000,1806.000000,1806.000000,1806.000000,1806.0,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000
mean,1016.775748,1070.420266,1113.347176,3.268439,0.0,53.654485,90.344961,71.773533,743.646733,36.690476,4.256826
std,599.331402,634.337523,676.201879,1.373428,0.0,13.385410,18.135166,14.568786,435.563107,12.999680,0.198270
min,0.000000,0.000000,0.000000,0.000000,0.0,34.000000,61.000000,47.000000,1.000000,6.000000,3.860730
25%,493.250000,522.250000,522.250000,3.100000,0.0,43.000000,76.000000,60.000000,350.250000,29.000000,4.102643
50%,1002.500000,1060.500000,1089.500000,3.600000,0.0,51.000000,87.000000,70.000000,753.500000,37.000000,4.248495
75%,1540.750000,1598.750000,1685.750000,4.000000,0.0,60.000000,103.000000,79.000000,1133.750000,46.000000,4.375757
max,2024.000000,2137.000000,2252.000000,5.000000,0.0,98.000000,132.000000,106.000000,1501.000000,64.000000,4.663439

In [ ]:
df_filtered['Company_Encoded'] = np.log(df_filtered['Company_Encoded'])

In [ ]:
df_filtered['Log Avg Salary'] = np.sqrt(df_filtered['Log Avg Salary'])
df_filtered['Max Salary (K)'] = np.log(df_filtered['Max Salary (K)'])
df_filtered['Min Salary (K)'] = np.log(df_filtered['Min Salary (K)'])

In [ ]:
df_filtered.describe()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1806.000000,1806.000000,1806.000000,1806.000000,1806.0,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000
mean,1016.775748,1070.420266,1113.347176,3.268439,0.0,3.953735,4.483971,71.773533,6.291620,36.690476,2.062650
std,599.331402,634.337523,676.201879,1.373428,0.0,0.236729,0.197558,14.568786,1.019781,12.999680,0.047979
min,0.000000,0.000000,0.000000,0.000000,0.0,3.526361,4.110874,47.000000,0.000000,6.000000,1.964874
25%,493.250000,522.250000,522.250000,3.100000,0.0,3.761200,4.330733,60.000000,5.858646,29.000000,2.025498
50%,1002.500000,1060.500000,1089.500000,3.600000,0.0,3.931826,4.465908,70.000000,6.624729,37.000000,2.061188
75%,1540.750000,1598.750000,1685.750000,4.000000,0.0,4.094345,4.634729,79.000000,7.033286,46.000000,2.091831
max,2024.000000,2137.000000,2252.000000,5.000000,0.0,4.584967,4.882802,106.000000,7.313887,64.000000,2.159500

In [ ]:
# Function to detect and convert data type
def convert_data_type(df_filtered):
    for column in df_filtered.columns:
        if df_filtered[column].dtype == 'object':
            if df_filtered[column].nunique() <= 10:  # Assume it's categorical if unique values are less than or equal to 10
                df_filtered[column] = df_filtered[column].astype('category')
            else:
                try:
                    df_filtered[column] = pd.to_numeric(df_filtered[column])
                except ValueError:
                    pass
        elif df_filtered[column].dtype == 'int64':
            if df_filtered[column].nunique() == 2 and df_filtered[column].min() == 0 and df_filtered[column].max() == 1:
                df_filtered[column] = df_filtered[column].astype('bool')
    return df_filtered

# Convert data type of all columns
df_filtered = convert_data_type(df_filtered)

In [ ]:
df=df_filtered.drop(columns=[	'Unnamed: 0.2'	,'Unnamed: 0.1'	,'Unnamed: 0'])

In [ ]:
df.head(3)

,Rating,Company Name,Easy Apply,Salary Estimate Cleaned,Min Salary (K),Max Salary (K),Avg Salary (K),Job City,Job State,HQ City,...,Job Title Simplified_Data Scientist,Job Title Simplified_Engineer,Job Title Simplified_Intern,Job Title Simplified_Lead Analyst,Job Title Simplified_Manager,Job Title Simplified_Senior Analyst,Job Title Group,Job Title Cleaned,Salary Range (K),Log Avg Salary
0,3.2,Vera Institute of Justice,0.0,37-66,3.610918,4.189655,51.0,New York,NY,New York,...,False,False,False,False,False,False,Mid-level Data Analyst,Analyst,29.0,1.985342
1,3.8,Visiting Nurse Service of New York,0.0,37-66,3.610918,4.189655,51.0,New York,NY,New York,...,False,False,False,False,False,False,Data Quality Analyst,Analyst,29.0,1.985342
2,3.4,Squarespace,0.0,37-66,3.610918,4.189655,51.0,New York,NY,New York,...,False,False,False,False,False,True,Senior Data Analyst,Senior Analyst,29.0,1.985342

In [ ]:
df=df.to_csv("/content/drive/MyDrive/sp_19_app/finalcleaned_dataset.csv")

In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/sp_19_app/finalcleaned_dataset.csv")

In [ ]:
df.describe()

,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1806.000000,1806.000000,1806.0,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000,1806.000000
mean,941.878738,3.268439,0.0,3.953735,4.483971,71.773533,6.291620,36.690476,2.062650
std,550.457778,1.373428,0.0,0.236729,0.197558,14.568786,1.019781,12.999680,0.047979
min,0.000000,0.000000,0.0,3.526361,4.110874,47.000000,0.000000,6.000000,1.964874
25%,463.250000,3.100000,0.0,3.761200,4.330733,60.000000,5.858646,29.000000,2.025498
50%,944.500000,3.600000,0.0,3.931826,4.465908,70.000000,6.624729,37.000000,2.061188
75%,1425.750000,4.000000,0.0,4.094345,4.634729,79.000000,7.033286,46.000000,2.091831
max,1881.000000,5.000000,0.0,4.584967,4.882802,106.000000,7.313887,64.000000,2.159500