<a href="https://colab.research.google.com/github/khushimalik3122/salary-predictor-19/blob/main/sp_19_outlier_cleaner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [89]:
import pandas as pd

In [90]:
df_original = pd.read_csv("/content/drive/MyDrive/sp_19_app/cleaned_dataset.csv")

In [91]:
df_original.describe()

,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,2025.000000,2025.000000,2025.000000,2025.0,2025.000000,2025.000000,2025.000000,2025.000000,2025.000000,2025.000000
mean,1065.206914,1107.399012,3.271556,0.0,53.007901,88.540741,70.550617,744.205926,35.532840,4.227130
std,618.779868,660.009950,1.376992,0.0,15.664149,22.239699,17.998724,436.974107,13.754088,0.256482
min,0.000000,0.000000,0.000000,0.0,27.000000,44.000000,39.000000,0.000000,6.000000,3.676301
25%,535.000000,535.000000,3.100000,0.0,42.000000,74.000000,59.000000,349.000000,26.000000,4.077537
50%,1070.000000,1099.000000,3.600000,0.0,50.000000,87.000000,69.000000,754.000000,35.000000,4.234107
75%,1576.000000,1663.000000,4.000000,0.0,60.000000,103.000000,80.000000,1146.000000,46.000000,4.382027
max,2137.000000,2252.000000,5.000000,0.0,98.000000,151.000000,120.000000,1501.000000,64.000000,4.787492

In [93]:
import numpy as np

# Define the columns and methods
columns = {
    'Rating': 'IQR',
    'Easy Apply': 'Z-Score',
    'Min Salary (K)': 'IQR',
    'Max Salary (K)': 'IQR',
    'Avg Salary (K)': 'IQR',
    'Company_Encoded': 'None',
    'Salary Range (K)': 'IQR',
    'Log Avg Salary': 'Z-Score'
}

# Define the thresholds
thresholds = {
    'Easy Apply': 2,
    'Log Avg Salary': 2
}

# Apply the methods
for column, method in columns.items():
    if method == 'IQR':
        Q1 = df_original[column].quantile(0.25)
        Q3 = df_original[column].quantile(0.75)
        IQR = Q3 - Q1
        df = df_original[~((df_original[column] < (Q1 - 1.5 * IQR)) | (df_original[column] > (Q3 + 1.5 * IQR)))]
    elif method == 'Z-Score':
        threshold = thresholds[column]
        z_scores = np.abs((df_original[column] - df_original[column].mean()) / df_original[column].std())
        df = df_original[z_scores < threshold]
    elif method == 'None':
        pass  # No outlier removal for this column

print("Original dataset shape:", df_original.shape)
print("Filtered dataset shape:", df.shape)

Original dataset shape: (2025, 173)
Filtered dataset shape: (1882, 173)

In [94]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1882.000000,1882.000000,1882.000000,1882.0,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000
mean,1068.931456,1111.293836,3.266578,0.0,53.773645,90.071732,71.697662,747.840595,36.298087,4.251692
std,625.983745,667.517755,1.377824,0.0,14.672204,19.282413,15.900123,435.806632,12.904956,0.218585
min,0.000000,0.000000,0.000000,0.0,30.000000,53.000000,41.000000,0.000000,6.000000,3.725693
25%,529.250000,529.250000,3.100000,0.0,43.000000,76.000000,59.000000,358.250000,29.000000,4.085976
50%,1056.500000,1085.500000,3.600000,0.0,51.000000,87.000000,69.000000,759.000000,36.000000,4.241327
75%,1583.750000,1670.750000,4.000000,0.0,60.000000,103.000000,80.000000,1146.750000,46.000000,4.382027
max,2137.000000,2252.000000,5.000000,0.0,98.000000,132.000000,113.000000,1501.000000,64.000000,4.727388

In [96]:
columns = {
    'Rating': 'IQR',
    'Easy Apply': 'None',
    'Min Salary (K)': 'IQR',
    'Max Salary (K)': 'IQR',
    'Avg Salary (K)': 'IQR',
    'Company_Encoded': 'None',
    'Salary Range (K)': 'IQR',
    'Log Avg Salary': 'IQR'
}

# Apply the methods
for column, method in columns.items():
    if method == 'IQR':
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        df_filtered = df[~((df[column] < (Q1 - 2.5 * IQR)) | (df[column] > (Q3 + 2.5 * IQR)))]
    elif method == 'None':
        pass  # No outlier removal for this column

print("Original dataset shape:", df_original.shape)
print("Filtered dataset shape:", df_filtered.shape)

Original dataset shape: (2025, 173)
Filtered dataset shape: (1882, 173)

In [97]:
df_filtered.describe()

,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1882.000000,1882.000000,1882.000000,1882.0,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000
mean,1068.931456,1111.293836,3.266578,0.0,53.773645,90.071732,71.697662,747.840595,36.298087,4.251692
std,625.983745,667.517755,1.377824,0.0,14.672204,19.282413,15.900123,435.806632,12.904956,0.218585
min,0.000000,0.000000,0.000000,0.0,30.000000,53.000000,41.000000,0.000000,6.000000,3.725693
25%,529.250000,529.250000,3.100000,0.0,43.000000,76.000000,59.000000,358.250000,29.000000,4.085976
50%,1056.500000,1085.500000,3.600000,0.0,51.000000,87.000000,69.000000,759.000000,36.000000,4.241327
75%,1583.750000,1670.750000,4.000000,0.0,60.000000,103.000000,80.000000,1146.750000,46.000000,4.382027
max,2137.000000,2252.000000,5.000000,0.0,98.000000,132.000000,113.000000,1501.000000,64.000000,4.727388

In [98]:
df_filtered['Company_Encoded'] = np.log(df_filtered['Company_Encoded'])

/usr/local/lib/python3.11/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [99]:
df_filtered['Log Avg Salary'] = np.sqrt(df_filtered['Log Avg Salary'])
df_filtered['Max Salary (K)'] = np.log(df_filtered['Max Salary (K)'])
df_filtered['Min Salary (K)'] = np.log(df_filtered['Min Salary (K)'])

In [100]:
df_filtered.describe()

,Unnamed: 0.1,Unnamed: 0,Rating,Easy Apply,Min Salary (K),Max Salary (K),Avg Salary (K),Company_Encoded,Salary Range (K),Log Avg Salary
count,1882.000000,1882.000000,1882.000000,1882.0,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000,1882.000000
mean,1068.931456,1111.293836,3.266578,0.0,3.950335,4.477832,71.697662,-inf,36.298087,2.061282
std,625.983745,667.517755,1.377824,0.0,0.259159,0.213814,15.900123,NaN,12.904956,0.053032
min,0.000000,0.000000,0.000000,0.0,3.401197,3.970292,41.000000,-inf,6.000000,1.930206
25%,529.250000,529.250000,3.100000,0.0,3.761200,4.330733,59.000000,5.881230,29.000000,2.021380
50%,1056.500000,1085.500000,3.600000,0.0,3.931826,4.465908,69.000000,6.632002,36.000000,2.059448
75%,1583.750000,1670.750000,4.000000,0.0,4.094345,4.634729,80.000000,7.044687,46.000000,2.093329
max,2137.000000,2252.000000,5.000000,0.0,4.584967,4.882802,113.000000,7.313887,64.000000,2.174256

In [101]:
df_cleaned=df_filtered
print(df_cleaned.columns)

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Rating', 'Company Name', 'Easy Apply',
       'Salary Estimate Cleaned', 'Min Salary (K)', 'Max Salary (K)',
       'Avg Salary (K)', 'Job City',
       ...
       'Job Title Simplified_Data Scientist', 'Job Title Simplified_Engineer',
       'Job Title Simplified_Intern', 'Job Title Simplified_Lead Analyst',
       'Job Title Simplified_Manager', 'Job Title Simplified_Senior Analyst',
       'Job Title Group', 'Job Title Cleaned', 'Salary Range (K)',
       'Log Avg Salary'],
      dtype='object', length=173)

In [102]:
print(df_cleaned.dtypes)

Unnamed: 0.1                             int64
Unnamed: 0                               int64
Rating                                 float64
Company Name                            object
Easy Apply                             float64
                                        ...
Job Title Simplified_Senior Analyst       bool
Job Title Group                         object
Job Title Cleaned                       object
Salary Range (K)                       float64
Log Avg Salary                         float64
Length: 173, dtype: object

In [103]:
# Function to detect and convert data type
def convert_data_type(df_cleaned):
    for column in df_cleaned.columns:
        if df_cleaned[column].dtype == 'object':
            if df_cleaned[column].nunique() <= 10:  # Assume it's categorical if unique values are less than or equal to 10
                df_cleaned[column] = df_cleaned[column].astype('category')
            else:
                try:
                    df_cleaned[column] = pd.to_numeric(df_cleaned[column])
                except ValueError:
                    pass
        elif df_cleaned[column].dtype == 'int64':
            if df_cleaned[column].nunique() == 2 and df_cleaned[column].min() == 0 and df_cleaned[column].max() == 1:
                df_cleaned[column] = df_cleaned[column].astype('bool')
    return df

# Convert data type of all columns
df_cleaned = convert_data_type(df)

<ipython-input-103-74a65b0fb79f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df_cleaned[column].astype('category')

In [105]:
print(df_cleaned.dtypes)

Unnamed: 0.1                              int64
Unnamed: 0                                int64
Rating                                  float64
Company Name                             object
Easy Apply                              float64
                                         ...
Job Title Simplified_Senior Analyst        bool
Job Title Group                          object
Job Title Cleaned                      category
Salary Range (K)                        float64
Log Avg Salary                          float64
Length: 173, dtype: object

In [106]:
df=df_cleaned.drop(columns=['Unnamed: 0','Unnamed: 0.1'])

In [107]:
pd=df_cleaned.to_csv("/content/drive/MyDrive/sp_19_app/cleaned_dataset.csv")